#!/bin/sh

storage(){
    if [ ! -d "kaddio-storage" ] ; then
        echo "Creating kaddio-storage folder"
        sudo mkdir kaddio-storage
    else
        echo "Found kaddio-storage folder, won't touch"
    fi
}

env(){
    if [ ! -d "env.sh" ] ; then
        echo "Creating env.sh defaults"
        cp kaddio/scripts/env.sh-defaults .
        mv env.sh-defaults env.sh
        sudo chmod 755 env.sh
    else
        echo "Found env.sh, won't copy"
    fi
}

meteor(){
    curl https://install.meteor.com/ | sh
}

npm(){
    meteor npm install --no-package-lock
}

storage
env
meteor
npm

echo "Success :) Go ahead and configure env.sh, then start Kaddio"
exit 0

# git config credential.helper store
