#!/bin/sh

# This is the Kaddio ESA install script!
#
#
# MAC AND LINUX:
#   Just open up your terminal and type:
#
#     curl https://kaddio.com/install-esa | sh
#
#   Kaddio currently supports Linux: x86 systems

clone(){
    if [ ! -d "kaddio" ]; then
        echo "Welcome to the Kaddio Enterprise Stand alone installer"
        git clone https://github.com/kaddio/kaddio.git
        cd kaddio
        git checkout malmoe-install-v2
        cd ..
    else
        echo "Already cloned?"
        exit 1
    fi
}

install(){
    ./kaddio/scripts/install.sh
}

bootstrap(){
    set -e
    set -u

    echo "Installing Kaddio ESA."

    clone
    install

    exit 0
}

# Run install function
bootstrap
