#!/bin/sh

# This is the Kaddio ESA install script!
#
#
# MAC AND LINUX:
#   Just open up your terminal and type:
#
#     curl https://kaddio.com/install-esa | sh
#
#   Kaddio currently supports Linux: x86 systems

# Place everything in a function

clone(){
    if [ ! -d "kaddio" ]; then
        echo "Cloning repo"
        git clone https://github.com/kaddio/kaddio.git
        git checkout malmoe-install-v2
    else
        echo "Already cloned?"
        exit 1
    fi
}

install(){
    ./kaddio/scripts/install.sh
}

bootstrap(){
    echo "Installing Kaddio ESA."
    clone
    install
    exit 0
}

# Run install function
bootstrap
